#JWT
security.jwt.expiration-minutes=3600
security.jwt.secret-key=0cb0bf995a8d59e348231f39ed80ca38f46d8f0da291bf74f17f5c2877c57918c3d88e0c95e930f850c27dbd8e5641ff

#DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true






