#JWT
security.jwt.expiration-minutes=3600
security.jwt.secret-key=0cb0bf995a8d59e348231f39ed80ca38f46d8f0da291bf74f17f5c2877c57918c3d88e0c95e930f850c27dbd8e5641ff

#DB
spring.datasource.url=jdbc:mysql://beblink-ddbb-mvp.cfiqwc4agxml.eu-west-1.rds.amazonaws.com:3306/BEBLINKMVP
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=BeBlink1994!
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.hikari.allow-pool-suspension=true
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never

#
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE





